# This is a sample config file.  Adjust the values and rename to config.ini.
# Keep config.ini within the config folder.

# List of possible values can be found at https://www.php.net/manual/en/timezones.php
[timezone]
timezone = "UTC"

# These are full paths & files where a license manager binary is located.
# They must have execute permissions for the web server user.
# FlexLM (lmutil) and Mathematica (monitorlm) are currently supported.
[lmtools]
lmutil_binary = "/usr/local/bin/lmutil"
monitorlm_binary = "/usr/local/bin/monitorlm"

# Database information.  Only db_type "mysql" is currently supported.
# Do NOT use these username and password values in production!
[database]
type = "mysql"
hostname="localhost"
username="phplw"
password="phplw_password"
database="licenses"

# License expiration alerts are sent to $notify_address.
# $reply_address is filled in the from and reply fields.
# Consider NOT using a "do not reply" address so that errors can be received.
# $smtp_tls is either "smtps", "starttls", or "none" to disable encryption.
# $smtp_port is usually either "465" (smtps) or "587" (starttls).
# License alert emails are disabled when $send_email_notifications is set 0.
# Licenses expiring within $lead_time (in days) are included in the alerts.
[mail]
smtp_host = ""
smtp_login = ""
smtp_password = ""
smtp_tls = ""
smtp_port = ""
notify_address = ""
reply_address = ""
send_email_notifications = 0
lead_time = 30
smtp_debug = 0

# cache_dir specifies what directory is used to store/process cache files.
# /tmp is not advised.  $cache_lifetime is how long a cache file is retained
# in seconds. e.g. 7200 = 2 hours.
[cache]
dir = "/var/cache/phplw/"
lifetime = 7200

# Sets visibility of computer and user names on the license detail view page.
# Values are "show", "hide", or "obfuscate".
[visibility]
license_details_show_user = "show"
license_details_show_computer = "show"

# Make sure interval matches, in minutes, the cron schedule for license_util.php.
[collection]
interval = 10

# IMPORTANT: Change this to 0 when used in production!
# Allows debug logging when set to 1.
[debug]
debug = 0

# EOF
